class CampaignComponent {
  async updateCampaignStatus(campaign, status) {
    if (status === StatusState.Archived) {
      // do some staff and update the campaign
      // ...
      // ...
      // ...
    } else if (status === StatusState.Paused) {
      // do some other staff and update the campaign
      // ...
      // ...
    } else if (status === StatusState.Playing) {
      // do some other staff and update the campaign
      // ...
      // ...
      // ...
    }
  }
}
